// web/packages/view/src/NextPieces.tsx
import React from "react";
import styled from "@emotion/styled";
import * as model from "@deep-trinity/model";
import PieceContainer from "./PieceContainer";

const NextPiecesRoot = styled.div``;

export type NextPiecesProps = {
  pieces: ArrayLike<model.Piece>,
};

export const NextPieces: React.FC<NextPiecesProps> = props => {
  const elPieces = [];
  for (let i = 0; i < props.pieces.length; i++) {
    elPieces.push(
      <PieceContainer key={i} piece={props.pieces[i]}/>
    );
  }
  return (
    <NextPiecesRoot>
      {elPieces}
    </NextPiecesRoot>
  );
};

export default NextPieces;

// web/packages/view-svelte/src/NextPieces.svelte
<script lang="ts">
  import PieceComponent from "./Piece.svelte";
  import { type Piece } from "@deep-trinity/model";
  export let pieces: ArrayLike<Piece>;
</script>

<div>
  {#each pieces as p}
    <div class="piece piece-{p}">
      <PieceComponent piece={p}></PieceComponent>
    </div>
  {/each}
</div>

<style>
</style>
