// web/packages/view/src/Piece.tsx
import React from "react";
import * as model from "@deep-trinity/model";
import { useTheme } from "./theme";
import Grid, { GridProps } from "./Grid";

const define = (piece: model.Piece, width: number, height: number, nonEmptyPositions: [number, number][]): GridProps => {
  const cells = Array(width * height).fill(model.Cell.Empty);
  for (const pos of nonEmptyPositions) {
    cells[model.getIndex(width, pos[0], pos[1])] = model.pieceToCell(piece);
  }
  return { width, height, cells };
};

const pieceSpecs: {
  [piece in model.Piece]: GridProps;
} = {
  [model.Piece.S]: define(model.Piece.S, 3, 2, [[0, 0], [1, 0], [1, 1], [2, 1]]),
  [model.Piece.Z]: define(model.Piece.Z, 3, 2, [[0, 1], [1, 0], [1, 1], [2, 0]]),
  [model.Piece.L]: define(model.Piece.L, 3, 2, [[0, 0], [1, 0], [2, 0], [2, 1]]),
  [model.Piece.J]: define(model.Piece.J, 3, 2, [[0, 0], [1, 0], [2, 0], [0, 1]]),
  [model.Piece.I]: define(model.Piece.I, 4, 1, [[0, 0], [1, 0], [2, 0], [3, 0]]),
  [model.Piece.T]: define(model.Piece.T, 3, 2, [[0, 0], [1, 0], [2, 0], [1, 1]]),
  [model.Piece.O]: define(model.Piece.O, 2, 2, [[0, 0], [1, 0], [0, 1], [1, 1]]),
};

export type PieceProps = {
  piece: model.Piece,
};

export const Piece: React.FC<PieceProps> = props => {
  const theme = useTheme();
  return (
    <Grid {...pieceSpecs[props.piece]} borderStyle={theme.pieceCellBorderStyle}/>
  );
};

export default Piece;

// web/packages/view-svelte/src/Piece.svelte
<script lang="ts">
  import { Piece, Cell } from "@deep-trinity/model";
  import Grid from "./Grid.svelte";
  export let piece: Piece;

  const [E, S, Z, L, J, I, T, O] = [
    Cell.Empty,
    Cell.S,
    Cell.Z,
    Cell.L,
    Cell.J,
    Cell.I,
    Cell.T,
    Cell.O,
  ];
  const PIECE_GRIDS = {
    [Piece.S]: {
      numCols: 3,
      numRows: 2,
      cells: [S, S, E, E, S, S],
    },
    [Piece.Z]: {
      numCols: 3,
      numRows: 2,
      cells: [E, Z, Z, Z, Z, E],
    },
    [Piece.L]: {
      numCols: 3,
      numRows: 2,
      cells: [L, L, L, E, E, L],
    },
    [Piece.J]: {
      numCols: 3,
      numRows: 2,
      cells: [J, J, J, J, E, E],
    },
    [Piece.I]: {
      numCols: 4,
      numRows: 1,
      cells: [I, I, I, I],
    },
    [Piece.T]: {
      numCols: 3,
      numRows: 2,
      cells: [T, T, T, E, T, E],
    },
    [Piece.O]: {
      numCols: 2,
      numRows: 2,
      cells: [O, O, O, O],
    },
  };

  $: g = PIECE_GRIDS[piece];
</script>

<div class="piece">
  <Grid cells={g.cells} numCols={g.numCols} numRows={g.numRows}></Grid>
</div>

<style>
  .piece {
    --grid-border: var(--piece-grid-border, none);
    --grid-cell-border: var(--piece-cell-border);
    --grid-empty-cell-border: var(--piece-empty-cell-border, 1px solid #fff);
  }
</style>
